{
  "formatVersion": "1.1",
  "component": {
    "group": "au.com.dius.pact.core",
    "module": "model",
    "version": "4.2.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "m4qqoikneffwnayeffkuhz2lda"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "au.com.dius.pact.core",
          "module": "support",
          "version": {
            "requires": "4.2.14"
          }
        },
        {
          "group": "au.com.dius.pact.core",
          "module": "pactbroker",
          "version": {
            "requires": "4.2.14"
          }
        }
      ],
      "files": [
        {
          "name": "model-4.2.14.jar",
          "url": "model-4.2.14.jar",
          "size": 553880,
          "sha512": "0370eca4a41636969c71ddc5dd4afc7d6e0a61da77c4ca196c952436e8dcd082dc75d6469003dff9eb3a6da6a874a7e6115d57a86f17c7dc7c17cda704b0d7ec",
          "sha256": "3a5fbbc5c24070b9472f82bb6bb639c43bf99e1e717d2846286a3a7e4b86225c",
          "sha1": "c7a79f1569de4af5497b780c0526f19a975aa743",
          "md5": "5782b5f4422d942fba78f41784c01a31"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "com.github.mifmif",
          "module": "generex",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "javax.mail",
          "module": "mail",
          "version": {
            "requires": "1.5.0-b01"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.28"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "1.27"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http-jvm",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "au.com.dius.pact.core",
          "module": "support",
          "version": {
            "requires": "4.2.14"
          }
        },
        {
          "group": "au.com.dius.pact.core",
          "module": "pactbroker",
          "version": {
            "requires": "4.2.14"
          }
        }
      ],
      "files": [
        {
          "name": "model-4.2.14.jar",
          "url": "model-4.2.14.jar",
          "size": 553880,
          "sha512": "0370eca4a41636969c71ddc5dd4afc7d6e0a61da77c4ca196c952436e8dcd082dc75d6469003dff9eb3a6da6a874a7e6115d57a86f17c7dc7c17cda704b0d7ec",
          "sha256": "3a5fbbc5c24070b9472f82bb6bb639c43bf99e1e717d2846286a3a7e4b86225c",
          "sha1": "c7a79f1569de4af5497b780c0526f19a975aa743",
          "md5": "5782b5f4422d942fba78f41784c01a31"
        }
      ]
    }
  ]
}
