{
  "formatVersion": "1.1",
  "component": {
    "group": "au.com.dius.pact.core",
    "module": "pactbroker",
    "version": "4.2.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "m4qqoikneffwnayeffkuhz2lda"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        },
        {
          "group": "au.com.dius.pact.core",
          "module": "support",
          "version": {
            "requires": "4.2.14"
          }
        },
        {
          "group": "com.michael-bull.kotlin-result",
          "module": "kotlin-result",
          "version": {
            "requires": "1.1.12"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "pactbroker-4.2.14.jar",
          "url": "pactbroker-4.2.14.jar",
          "size": 125216,
          "sha512": "eac38b30f86c017ddc1173e88050102bffd8bf7179dfa82e12c7bb4f7b5b353aa6f8db331550008ae4dfa1881391f86a6f87b53aa3a8e00296a821fcf8f38677",
          "sha256": "a44ca2cc52ee15447cfb3a6b78692b584145a7f46365d1488db6680b6d70e5b8",
          "sha1": "fcfa13da7591222f1b564d3fb244517b6064496e",
          "md5": "6c544284f8ac1d59fa251d431b55928e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "2.0.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.28"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        },
        {
          "group": "au.com.dius.pact.core",
          "module": "support",
          "version": {
            "requires": "4.2.14"
          }
        },
        {
          "group": "com.michael-bull.kotlin-result",
          "module": "kotlin-result",
          "version": {
            "requires": "1.1.12"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "pactbroker-4.2.14.jar",
          "url": "pactbroker-4.2.14.jar",
          "size": 125216,
          "sha512": "eac38b30f86c017ddc1173e88050102bffd8bf7179dfa82e12c7bb4f7b5b353aa6f8db331550008ae4dfa1881391f86a6f87b53aa3a8e00296a821fcf8f38677",
          "sha256": "a44ca2cc52ee15447cfb3a6b78692b584145a7f46365d1488db6680b6d70e5b8",
          "sha1": "fcfa13da7591222f1b564d3fb244517b6064496e",
          "md5": "6c544284f8ac1d59fa251d431b55928e"
        }
      ]
    }
  ]
}
