{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "2.5.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "xab3cdtiarcmhang6i4xnp4woe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.53"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "9.0.53"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.53"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.5.5.jar",
          "url": "spring-boot-starter-tomcat-2.5.5.jar",
          "size": 4797,
          "sha512": "8a63d8deadf4316bcac4e92c3019a0aa20035811b1d78886885c82b3b6d4f5253eceb8b6feb1e0d8156b76369b84434ffe421a0eaa9a859c937c9fc343a7b688",
          "sha256": "7f599dedb52d1ee8e5e955e6d0238e1f3a5a0864ca5541f48e53a08de444ea7a",
          "sha1": "3fb58add8060ff5a6a17e08eeabca1e823c2f04a",
          "md5": "8ea2a43c623c5df4a62c793058376dc2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.53"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "9.0.53"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.53"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.5.5.jar",
          "url": "spring-boot-starter-tomcat-2.5.5.jar",
          "size": 4797,
          "sha512": "8a63d8deadf4316bcac4e92c3019a0aa20035811b1d78886885c82b3b6d4f5253eceb8b6feb1e0d8156b76369b84434ffe421a0eaa9a859c937c9fc343a7b688",
          "sha256": "7f599dedb52d1ee8e5e955e6d0238e1f3a5a0864ca5541f48e53a08de444ea7a",
          "sha1": "3fb58add8060ff5a6a17e08eeabca1e823c2f04a",
          "md5": "8ea2a43c623c5df4a62c793058376dc2"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.5.5.jar",
          "url": "spring-boot-starter-tomcat-2.5.5.jar",
          "size": 4797,
          "sha512": "8a63d8deadf4316bcac4e92c3019a0aa20035811b1d78886885c82b3b6d4f5253eceb8b6feb1e0d8156b76369b84434ffe421a0eaa9a859c937c9fc343a7b688",
          "sha256": "7f599dedb52d1ee8e5e955e6d0238e1f3a5a0864ca5541f48e53a08de444ea7a",
          "sha1": "3fb58add8060ff5a6a17e08eeabca1e823c2f04a",
          "md5": "8ea2a43c623c5df4a62c793058376dc2"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-tomcat-maven-optional",
          "version": "2.5.5"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.5.5.jar",
          "url": "spring-boot-starter-tomcat-2.5.5.jar",
          "size": 4797,
          "sha512": "8a63d8deadf4316bcac4e92c3019a0aa20035811b1d78886885c82b3b6d4f5253eceb8b6feb1e0d8156b76369b84434ffe421a0eaa9a859c937c9fc343a7b688",
          "sha256": "7f599dedb52d1ee8e5e955e6d0238e1f3a5a0864ca5541f48e53a08de444ea7a",
          "sha1": "3fb58add8060ff5a6a17e08eeabca1e823c2f04a",
          "md5": "8ea2a43c623c5df4a62c793058376dc2"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-tomcat-maven-optional",
          "version": "2.5.5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.5.5-javadoc.jar",
          "url": "spring-boot-starter-tomcat-2.5.5-javadoc.jar",
          "size": 4745,
          "sha512": "4f8e8ecd143437d8867bcf4b74b4783f88a6fb7fe13b1c2f5cb8e3a8d4cad48203818451ae115b6d606b33253ed52884054e4176aa34c798cdf32daca15c79c5",
          "sha256": "46e6a6e4f0db098ea9f91d941c8271bfdafcf16f84f2920a490a41e6f1b7e185",
          "sha1": "c726888d4068e5496dd9c1e70e137f04794fbc0f",
          "md5": "0b1296baa36519be8fcdb669168e99f1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.5.5-sources.jar",
          "url": "spring-boot-starter-tomcat-2.5.5-sources.jar",
          "size": 4744,
          "sha512": "fe1463b33f6f4f3b1003862a3abc7da6ab272a937d0f3a5a8219de94003b5aac1c9e58d9032a278a3ab233e4860bf59a0dae55911e0001b9fe9db5054fd89a12",
          "sha256": "d03385ecf3ed6fe548abe73c036a6812e4aae61ddd215a9f5fa1642ce624d098",
          "sha1": "860a4d212ade1e9272c7a55d9334a741c8f023dc",
          "md5": "06f287e57b88077a57a3e15ee64a09a6"
        }
      ]
    }
  ]
}
